import {StyleSheet, Dimensions, StatusBar} from 'react-native';
import {Color, FontFamily, FontSize} from '../../../global';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
const {width} = Dimensions.get('window');
const itemWidth = (width / 2.5) * 2;
const gap = (width - itemWidth) / 3.3;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  View1: {
    marginTop: '8%',
    paddingHorizontal: '5%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: StatusBar.currentHeight,
  },
  locationText: {
    fontFamily: FontFamily.montserratMedium,
    fontSize: 8,
    color: 'rgba(0, 0, 0, 0.45)',
  },
  locationText1: {
    fontFamily: FontFamily.montserratRegular,
    fontSize: FontSize.size_10,
    color: Color.colorBlack,
    marginLeft: '2%',
    width: wp('70%'),
  },
  cartBg: {
    backgroundColor: Color.colorBlack,
    borderRadius: 50,
    padding: '3%',
    justifyContent: 'center',
    width: wp('12%'),
    height: wp('12%'),
  },
  cartBg2: {
    backgroundColor: '#FF3B3D',
    borderRadius: 50,
    padding: 4,
    justifyContent: 'center',
    alignItems: 'center',
    width: wp('5%'),
    height: wp('5%'),
  },
  innertext: {
    fontFamily: FontFamily.montserratMedium,
    fontSize: 8,
    color: '#FFF',
  },
  cardBg: {
    width: wp('90%'),
    height: wp('37%'),
    borderRadius: 15,
    paddingLeft: '8%',
  },
  text1: {
    fontFamily: FontFamily.montserratSemiBold,
    fontSize: FontSize.size_12,
    marginTop: '2%',
    color: Color.colorBlack,
  },
  text2: {
    fontFamily: FontFamily.montserratRegular,
    fontSize: 6,
    marginTop: '4%',
    color: 'rgba(0, 0, 0, 0.45)',
  },
  moreBtn: {
    width: wp('14%'),
    borderRadius: 20,
    padding: '2%',
    marginTop: '10%',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  moretext: {
    fontFamily: FontFamily.montserratSemiBold,
    color: '#fff',
    textAlign: 'center',
    fontSize: 7,
    zIndex: 1,
  },
  innerView1: {
    marginTop: '5%',
    marginLeft: '5%',
    marginRight: '5%',
  },
  innerView2: {
    marginTop: '8%',
    marginLeft: '5%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  addFamilyBtn: {
    backgroundColor: Color.colorWhite,
    padding: 8,
    marginHorizontal: 5,
    borderRadius: 35,
    flexDirection: 'row',
    alignItems: 'center',
  },
  addFamilyTxt: {
    color: Color.colorBlack,
    fontSize: 9,
    fontFamily: FontFamily.montserratMedium,
  },
  icon: {
    marginRight: 8,
    width: wp('5%'),
    height: wp('5%'),
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardText: {
    fontFamily: FontFamily.montserratMedium,
    fontSize: FontSize.size_15,
    color: Color.colorBlack,
    marginTop: '5%',
    marginLeft: '5%',
    marginRight: '5%',
  },
  card: {
    overflow: 'hidden',
    height: wp('50%'),
    borderRadius: 15,
    padding: '8%',
    width: itemWidth,
    marginRight: gap,
  },
  cardInnerText: {
    fontFamily: FontFamily.montserratSemiBold,
    color: Color.colorWhite,
    fontSize: 16,
    width: wp('100%'),
  },
  ExpText: {
    fontFamily: FontFamily.montserratMedium,
    fontSize: 5,
    color: '#FFF',
    marginTop: '14%',
  },
  datetext: {
    fontFamily: FontFamily.montserratSemiBold,
    fontSize: 9,
    color: Color.colorWhite,
  },
  cardText2: {
    fontFamily: FontFamily.montserratMedium,
    color: Color.colorWhite,
    fontSize: 5,
    marginTop: '15%',
  },
  cardName1: {
    fontFamily: FontFamily.montserratMedium,
    fontSize: 5,
    color: '#FFF',
    marginTop: '14%',
  },
  cardNameText: {
    fontFamily: FontFamily.montserratSemiBold,
    fontSize: 9,
    color: Color.colorWhite,
    width: wp('50%'),
  },
  service: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginHorizontal: '2%',
    marginTop: '5%',
  },
  bgView: {
    alignItems: 'center',
    alignSelf: 'center',
    paddingVertical: '5%',
    marginHorizontal: '3%',
  },
  serviceImage: {
    alignSelf: 'center',
    alignItems: 'center',
    resizeMode: 'stretch',
    width: wp('18%'),
    height: wp('16%'),
  },
  planTripText: {
    fontFamily: FontFamily.montserratRegular,
    fontSize: 8,
    color: Color.colorBlack,
    textAlign: 'center',
    marginTop: '25%',
  },
  card12: {
    height: wp('24%'),
    backgroundColor: '#fff',
    marginHorizontal: 5,
    borderRadius: 15,
    padding: '5%',
  },
  Text12: {
    fontFamily: FontFamily.montserratSemiBold,
    fontSize: 7,
    color: Color.colorBlack,
    marginLeft: '7%',
    marginTop: '3%',
  },
  Text21: {
    fontFamily: FontFamily.montserratRegular,
    fontSize: 3.5,
    color: Color.colorBlack,
    marginLeft: '7%',
    marginTop: '3%',
    marginBottom: '3%',
  },
  MoreBtn12: {
    fontFamily: FontFamily.montserratSemiBold,
    fontSize: 4,
    color: Color.colorBlack,
    width: wp('7%'),
    color: Color.colorWhite,
    textAlign: 'center',
    borderRadius: 10,
    paddingVertical: '1%',
    marginTop: '6%',
    marginLeft: '14%',
  },
  innerStyle12: {
    marginLeft: '5%',
    marginTop: '7%',
    borderRadius: 2,
    borderLeftWidth: 2,
  },
  driveText: {
    fontFamily: FontFamily.montserratRegular,
    fontSize: FontSize.size_13,
    color: 'rgba(0, 0, 0, 0.76)',
    marginLeft: '5%',
    marginTop: '15%',
  },
  lifeStyleText: {
    fontFamily: FontFamily.genosbold,
    fontSize: 60,
    color: '#636363',
    marginLeft: '5%',
    marginTop: '1%',
  },
  //New Styles
  resView: {
    marginRight: 9,
    width: wp('20%'),
    height: wp('18%'),
    backgroundColor: Color.colorWhite,
    borderRadius: 15,
    elevation: 2,
    overflow: 'hidden',
  },
  circle: {
    width: wp('12%'),
    height: wp('12%'),
    borderRadius: 99,
    backgroundColor: '#FFC727',
    marginLeft: '50%',
    marginTop: '-13%',
  },
  continental: {
    fontFamily: FontFamily.montserratSemiBold,
    fontSize: 7,
    color: Color.colorBlack,
    textAlign: 'center',
    marginTop: '8%',
  },
  shimmer2: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '1%',
  },
  shineContainer: {
    ...StyleSheet.absoluteFillObject, // Position container absolutely to fill parent
    justifyContent: 'center',
    alignItems: 'center',
    resizeMode: 'contain',
  },
  shine: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
});