import {Platform, StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import {Color, FontFamily, FontSize} from '../../../global';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  image1: {
    height: hp('5%'),
    width: wp('10%'),
    borderRadius: 100,
  },
  container1: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: wp('5%'),
    marginRight: wp('5%'),
    marginTop: Platform.OS == 'ios' ? hp('3%') : hp('7%'),
    marginBottom: hp('3%'),
    columnGap: wp('45%'),
  },
  container2: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    columnGap: wp('5%'),
  },
  text1: {
    color: Color.colorBlack,
    fontFamily: FontFamily.montserratMedium,
    fontSize: 7,
  },
  text2: {
    color: Color.colorBlack,
    fontFamily: FontFamily.montserratSemiBold,
    fontSize: 9,
  },
  icon1: {
    padding: wp('2%'),
    backgroundColor: Color.colorWhite,
    borderRadius: 15,
    marginRight: '50%',
    marginTop: '3%',
  },
  cardBackground: {
    width: wp('80%'),
    height: hp('22%'),
    padding: '3%',
    justifyContent: 'flex-start',
  },
  cardno: {
    fontSize: 14,
    fontFamily: FontFamily.montserratSemiBold,
    color: Color.colorWhite,
  },
  carddetails: {
    fontSize: 7.64,
    fontFamily: FontFamily.montserratSemiBold,
    color: Color.colorWhite,
  },
  sidebuttons: {
    flexDirection: 'column',
  },
  container3: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginRight: wp('5%'),
  },
  trans: {
    transform: [{rotate: '90deg'}],
    height: '12%',
    width: '47%',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    borderRadius: 10,
  },
  sub: {
    marginTop: '9%',
    rowGap: hp('7%'),
  },
  sidetxt: {
    color: '#ffffff',
    fontSize: 5.39,
    fontFamily: 'Montserrat-SemiBold',
  },
  icon2: {
    backgroundColor: '#ffffff',
    width: wp('5%'),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    paddingLeft: '5%',
  },
  viewcard: {
    borderWidth: 1,
    borderColor: '#ffffff',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    height: hp('3%'),
    width: wp('15%'),
  },
  container4: {
    marginLeft: wp('5%'),
    marginRight: wp('5%'),
    marginTop: hp('-6%'),
  },
  container5: {
    marginLeft: wp('5%'),
    marginRight: wp('5%'),
    marginTop: hp('5%'),
  },
  head: {
    fontSize: 12,
    fontFamily: 'Montserrat-Medium',
    fontWeight: '300',
    color: '#000000',
    marginBottom: hp('3%'),
  },
  list: {
    paddingTop: wp('2%'),
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  icontxt3: {
    fontSize: 6,
    color: '#000000',
    paddingTop: '2%',
    fontFamily: 'Montserrat-Medium',
  },
  iconimage3: {
    height: hp('2.7%'),
    width: wp('6%'),
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: wp('90%'),
    backgroundColor: '#FFF',
    borderRadius: 16,
    alignItems: 'flex-start',
    height: hp('25%'),
    rowGap: hp('5%'),
    flexDirection: 'row',
  },
  modaltext: {
    color: Color.colorBlack,
    fontFamily: FontFamily.montserratMedium,
    fontSize: 6,
  },
  slide: {
    width: wp('90%'),
    height: hp('13.5%'),
    alignItems: 'flex-start',
    paddingLeft: wp('20%'),
    paddingTop: hp('2%'),
    paddingRight: wp('7%'),
    borderRadius: 10,
    marginHorizontal: wp('5%'),
    rowGap: hp('1%'),
    marginTop: hp('5%'),
  },
  slideTitle: {
    fontSize: 12,
    fontFamily: FontFamily.montserratSemiBold,
    color: Color.colorBlack,
  },
  slideDescription: {
    fontSize: 7,
    color: Color.colorGray,
    fontFamily: FontFamily.montserratRegular,
  },
  dotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginLeft: wp('80%'),
    marginTop: hp('1%'),
    marginRight: wp('5%'),
    marginBottom: hp('5%'),
  },
  linearGradient: {
    height: hp('3%'),
    width: wp('20%'),
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lineargradtxt: {
    fontFamily: FontFamily.montserratSemiBold,
    fontSize: 6,
    color: Color.colorWhite,
  },
  inactiveDot: {
    height: 8,
    width: 30,
    borderRadius: 5,
    marginHorizontal: 5,
    backgroundColor: '#D3D3D3',
  },
  activeDot: {
    height: 10,
    width: 10,
    borderRadius: 5,
    marginHorizontal: 5,
    backgroundColor: '#000',
  },
  modalback: {
    height: hp('20%'),
    width: wp('10%'),
    borderTopLeftRadius: 16,
  },
  modalcardcicon: {
    height: hp('3%'),
    width: wp('11%'),
  },
  cardslist: {},
  modalicontxt: {
    fontFamily: FontFamily.montserratMedium,
    fontSize: FontSize.size_12,
    color: Color.colorBlack,
  },
  carddetailscontainer: {
    height: hp('50%'),
    width: wp('100%'),
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    marginTop: hp('50%'),
  },
  modalcardbackground: {
    width: wp('76%'),
    height: hp('22%'),
    marginHorizontal: wp('7%'),
    padding: wp('10%'),
    justifyContent: 'space-between',
  },
  modalcardhead: {
    fontFamily: FontFamily.montserratSemiBold,
    fontSize: FontSize.size_15,
    color: Color.colorBlack,
  },
  modalcardname: {
    fontFamily: FontFamily.montserratSemiBold,
    fontSize: FontSize.size_8,
    color: Color.colorWhite,
  },
  cardbottomhead: {
    fontFamily: FontFamily.montserratMedium,
    fontSize: FontSize.size_12,
    color: Color.colorBlack,
  },
  cardbottomtext: {
    fontFamily: FontFamily.montserratRegular,
    fontSize: FontSize.size_9,
    color: Color.colorGray,
  },
  modalContentaction: {
    width: wp('90%'),
    backgroundColor: '#FFF',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    height: hp('35%'),
    rowGap: hp('5%'),
  },
  Imageaction: {
    width: wp('90%'),
    height: hp('15%'),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: hp('3%'),
  },
  actionhead: {
    fontFamily: FontFamily.montserratMedium,
    fontSize: FontSize.size_11,
    color: Color.colorBlack,
  },
});
