import {Platform, StatusBar, StyleSheet} from 'react-native';
import {Color, FontFamily} from '../../../global';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
export const styles = StyleSheet.create({
  backgroundImage: [
    {
      flex: 1,
      width: '100%',
      height: '100%',
      resizeMode: 'stretch',
      paddingTop: StatusBar.currentHeight,
    },
    Platform.OS == 'ios' && {
      paddingTop: '10%',
    },
  ],
  freeText: {
    fontSize: 21,
    color: '#263238',
    textAlign: 'left',
    fontFamily: FontFamily.montserratBold,
    marginHorizontal: '8%',
    marginTop: '5%',
  },
  titleText: {
    fontSize: 16,
    color: '#000',
    textAlign: 'left',
    fontFamily: FontFamily.montserratMedium,
    padding: '4%',
  },
  GetSpinsText: {
    fontSize: 11,
    color: '#FFFFFF',
    fontFamily: FontFamily.montserratMedium,
  },
  cardContainer: {
    marginBottom: 10,
  },
  cardImg: {
    width: wp('90%'),
    height: wp('35%'),
    alignSelf: 'center',
    borderRadius: 20,
    marginTop: '8%',
    overflow: 'hidden',
  },
  goGreentext: {
    fontSize: 17,
    color: '#FFFFFF',
    marginLeft: '9%',
    fontFamily: FontFamily.montserratSemiBold,
    padding: '5%',
  },
  descreptionText1: {
    fontSize: 10,
    color: '#FFFFFF',
    marginTop: '-2%',
    fontFamily: FontFamily.montserratMedium,
    marginLeft: '5%',
  },
  scanBox: {
    width: wp('25%'),
    height: wp('12%'),
    alignSelf: 'flex-start',
    borderTopRightRadius: 10,
    backgroundColor: '#FFFFFF',
    marginTop: '5%',
  },
  scanText: {
    fontSize: 10,
    color: 'rgba(0, 0, 0, 0.81)',
    textAlign: 'center',
    fontFamily: FontFamily.montserratMedium,
    marginTop: '9%',
  },
  input: {
    width: wp('55%'),
    padding: 3,
    borderRadius: 10,
    paddingLeft: '4%',
    backgroundColor: '#9DC8D2',
    color: Color.colorBlack,
    fontSize: 9,
    fontFamily: FontFamily.montserratRegular,
  },
  cancelButton: {
    width: wp('20%'),
    padding: 6,
    borderRadius: 23,
    marginLeft: '8%',
    marginTop: '6%',
  },
  icon: {
    marginTop: '7%',
  },
  cancelButtonText: {
    fontFamily: FontFamily.montserratSemiBold,
    color: Color.colorWhite,
    fontSize: 8,
    textAlign: 'center',
  },
  howToGetSpins: {
    flexDirection: 'row',
    marginLeft: '50%',
    marginTop: '-8%',
  },
  instructionsContainer: {
    marginTop: '5%',
  },
  digitContainer: {
    width: wp('8%'),
    padding: '1%',
    height: wp('8%'),
    backgroundColor: '#DBF2E2',
    borderRadius: 50,
    marginLeft: '4%',
  },
  digitText: {
    fontSize: 13,
    color: '#F9A738',
    textAlign: 'center',
    fontFamily: FontFamily.montserratBold,
  },
  verticalLine: {
    borderLeftWidth: 4,
    borderLeftColor: '#FFC727',
    borderStyle: 'dotted',
    height: wp('60%'),
    marginLeft: '7.5%',
  },
  verticalLine2: {
    borderLeftWidth: 4,
    borderLeftColor: '#FFC727',
    borderStyle: 'dotted',
    height: wp('15%'),
    marginLeft: '7.5%',
  },

  subTitle1: {
    fontSize: 16,
    color: '#000',
    fontFamily: FontFamily.montserratSemiBold,
    marginLeft: '8%',
    marginTop: '-8%',
  },
  subTitle2: {
    fontSize: 12,
    color: '#676767',
    fontFamily: FontFamily.montserratRegular,
    marginLeft: '8%',
  },
  subImg: {
    width: wp('60%'),
    height: wp('40%'),
    alignSelf: 'center',
    marginTop: '8%',
    overflow: 'hidden',
  },
  redCircle1: {
    width: wp('3%'),
    height: wp('3%'),
    borderRadius: 50,
    backgroundColor: 'red',
    marginLeft: '39%',
    marginTop: '1%',
  },
  redCircle2: {
    width: wp('3%'),
    height: wp('3%'),
    borderRadius: 50,
    backgroundColor: 'red',
    marginLeft: '45%',
    marginTop: '3%',
  },
  modalContent: {
    width: wp('80%'),
    height: wp('90%'),
    borderRadius: 36,
    alignItems: 'center',
    borderWidth: 7,
    borderColor: '#D5CBCB',
  },
  continueButton: {
    padding: '2%',
    borderRadius: 21,
    width: wp('45%'),
  },
  continueButtonText: {
    color: '#F1ED8A',
    fontSize: 20,
    fontFamily: FontFamily.montserratBold,
    textAlign: 'center',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  barcodeImg: {
    alignSelf: 'center',
    width: wp('20%'),
    height: wp('25%'),
    marginTop: '-5%',
  },
  descText: {
    fontFamily: FontFamily.montserratSemiBold,
    fontSize: 12,
    color: '#000',
    textAlign: 'center',
    marginTop: '5%',
  },
});
